// Defined constants

// ARTICLES
export const ARTICLES_RECIEVED = 'ARTICLES_RECIEVED';
export const ARTICLES_ADDED = 'ARTICLES_ADDED';

// READ/UNREAD
export const ARTICLE_VISITED = 'ARTICLE_VISITED';

// REDIRECTS
export const REDIRECT_DATA_RECIEVED = 'REDIRECT_DATA_RECIEVED';