// Defined constants

// App
export const APP_LOADED = 'APP_LOADED';
export const APP_START_LOADING = 'APP_START_LOADING';
export const APP_FINISH_LOADING = 'APP_FINISH_LOADING';
export const APP_GEOLOCATION_RECIEVED = 'APP_GEOLOCATION_RECIEVED';

// User
export const GET_USER_DATA = 'GET_USER_DATA';
export const USER_DATA_RECIEVED = 'USER_DATA_RECIEVED';
export const ANOTHER_USER_DATA_RECIEVED = 'ANOTHER_USER_DATA_RECIEVED';
export const USER_PHONES_RECIEVED = 'USER_PHONES_RECIEVED';
export const ALL_USER_DATA_RECIEVED = 'ALL_USER_DATA_RECIEVED';

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGED_ERROR = 'LOGGED_ERROR';
export const USER_REGISTRED = 'USER_REGISTRED';

export const USER_CREATEDTASKS_RECIEVED = 'USER_CREATEDTASKS_RECIEVED';
export const USER_PERFORMEDTASKS_RECIEVED = 'USER_PERFORMEDTASKS_RECIEVED';
export const USER_RESPONDEDTASKS_RECIEVED = 'USER_RESPONDEDTASKS_RECIEVED';
export const USER_FAVORITETASKS_RECIEVED = 'USER_FAVORITETASKS_RECIEVED';
export const USER_REVIEWS_RECIEVED = 'USER_REVIEWS_RECIEVED';
export const USER_TEAMS_RECIEVED = 'USER_TEAMS_RECIEVED';
export const USER_PHOTO_RECIEVED = 'USER_PHOTO_RECIEVED';
export const USER_BLOGS_RECIEVED = 'USER_BLOGS_RECIEVED';
export const USER_CAREERS_RECIEVED = 'USER_CAREERS_RECIEVED';
export const USER_EDUCATION_RECIEVED = 'USER_EDUCATION_RECIEVED';
export const USER_EDUCATION_IMAGES_RECIEVED = 'USER_EDUCATION_IMAGES_RECIEVED';
export const USER_SERVICES_RECIEVED = 'USER_SERVICES_RECIEVED';
export const USER_TAGS_RECIEVED = 'USER_TAGS_RECIEVED';
export const USER_RESPONDS_CHANGE = 'USER_RESPONDS_CHANGE';
export const USER_TASK_PROFILE = 'USER_TASK_PROFILE';
export const MY_TASK_COUNT = 'MY_TASK_COUNT';
export const MY_TASK_ALL = 'MY_TASK_ALL';
export const MY_TASK_RESPONDS = 'MY_TASK_RESPONDS';
export const MY_TASK_DELEGATE = 'MY_TASK_DELEGATE';
export const MY_TASK_CHOICE = 'MY_TASK_CHOICE';
export const MY_TASK_MAKE = 'MY_TASK_MAKE';
export const MY_TASK_ARHIV = 'MY_TASK_ARHIV';


export const PROFILE_USER_DATA_RECIEVED = 'PROFILE_USER_DATA_RECIEVED';
export const PROFILE_USER_CREATEDTASKS_RECIEVED = 'PROFILE_USER_CREATEDTASKS_RECIEVED';
export const PROFILE_USER_PERFORMEDTASKS_RECIEVED = 'PROFILE_USER_PERFORMEDTASKS_RECIEVED';
export const PROFILE_USER_REVIEWS_RECIEVED = 'PROFILE_USER_REVIEWS_RECIEVED';
export const PROFILE_USER_PHONES_RECIEVED = 'PROFILE_USER_PHONES_RECIEVED';
export const PROFILE_USER_TEAMS_RECIEVED = 'PROFILE_USER_TEAMS_RECIEVED';
export const PROFILE_USER_PHOTO_RECIEVED = 'PROFILE_USER_PHOTO_RECIEVED';
export const PROFILE_USER_BLOGS_RECIEVED = 'PROFILE_USER_BLOGS_RECIEVED';
export const PROFILE_USER_CAREERS_RECIEVED = 'PROFILE_USER_CAREERS_RECIEVED';
export const PROFILE_USER_EDUCATION_RECIEVED = 'PROFILE_USER_EDUCATION_RECIEVED';
export const PROFILE_USER_EDUCATION_IMAGES_RECIEVED = 'PROFILE_USER_EDUCATION_IMAGES_RECIEVED';
export const PROFILE_USER_SERVICES_RECIEVED = 'PROFILE_USER_SERVICES_RECIEVED';
export const PROFILE_USER_TAGS_RECIEVED = 'PROFILE_USER_TAGS_RECIEVED';

export const USER_TAGS_REPLACE = 'USER_TAGS_REPLACE';
export const USER_TAGS_ADD = 'USER_TAGS_ADD';

// Tags
export const TAGS_RECIEVED = 'TAGS_RECIEVED';
export const POPULAR_TAGS_RECIEVED = 'POPULAR_TAGS_RECIEVED';

// Service units
export const UNITS_RECIEVED = 'UNITS_RECIEVED';

// Tasks
export const TASKS_RECIEVED = 'TASKS_RECIEVED';
export const TASK_RECIEVED = 'TASK_RECIEVED';
export const TASKS_PRO_RECIEVED = 'TASKS_PRO_RECIEVED';
export const TASKS_BUSINESS_RECIEVED = 'TASKS_BUSINESS_RECIEVED';
export const AWAY_FROM_TASK = 'AWAY_FROM_TASK';
export const TASK_PERFORMER_CHANGED = 'TASK_PERFORMER_CHANGED';
export const TASK_EDITED = 'TASK_EDITED';

// Tasks filter
export const TASKS_FILTER_DATA_RECIEVED = 'TASKS_FILTER_DATA_RECIEVED';
export const TASKS_FILTER_CHANGED = 'TASKS_FILTER_CHANGED';
export const MYTASKS_FILTER_CHANGED = 'MYTASKS_FILTER_CHANGED';
export const TASK_FILTER_TAGS_RECIEVED = 'TASK_FILTER_TAGS_RECIEVED';
export const MYTASK_FILTER_TAGS_RECIEVED = 'MYTASK_FILTER_TAGS_RECIEVED';

// Tasks responds
export const TASK_RESPOND_DELETED = 'TASK_RESPOND_DELETED';
export const TASK_RESPOND_APPLIED = 'TASK_RESPOND_APPLIED';
export const MYTASK_RESPOND_DELETED = 'MYTASK_RESPOND_DELETED';
export const MYTASK_RESPOND_APPLIED = 'MYTASK_RESPOND_APPLIED';

export const MYTASKS_LOADED = 'MYTASKS_LOADED';

// Tasks performers
export const TASK_PERFORMER_DELETED = 'TASK_PERFORMER_DELETED';
export const MYTASK_PERFORMER_DELETED = 'MYTASK_PERFORMER_DELETED';

export const USER_PRIVATE_STATUS_CHANGE = 'USER_PRIVATE_STATUS_CHANGE';

// Teams
export const TEAM_CONTACTS_RECIEVED = 'TEAM_CONTACTS_RECIEVED';
export const TEAM_QUERY_RECIEVED = 'TEAM_QUERY_RECIEVED';
export const TEAM_RECOM_RECIEVED = 'TEAM_RECOM_RECIEVED';
export const TEAM_RECOM_PERFORMERS_RECIEVED = 'TEAM_RECOM_PERFORMERS_RECIEVED';
export const TEAM_DATA_LOADED = 'TEAM_DATA_LOADED';
export const TEAM_GROUPS_RECIEVED = 'TEAM_GROUPS_RECIEVED';
export const TEAM_QUERY_ACCEPTED = 'TEAM_QUERY_ACCEPTED';
export const TEAM_QUERY_CANCELED = 'TEAM_QUERY_CANCELED';
export const TEAM_INVITED = 'TEAM_INVITED';
export const TEAM_GROUP_ADDED = 'TEAM_GROUP_ADDED';
export const TEAM_USER_GROUP_APPLIED = 'TEAM_USER_GROUP_APPLIED';
export const TEAM_USER_GROUP_REMOVED = 'TEAM_USER_GROUP_REMOVED';
export const TEAM_FILTER_TAGS_RECIEVED = 'TEAM_FILTER_TAGS_RECIEVED';
export const TEAM_FILTER_CHANGED = 'TEAM_FILTER_CHANGED';

// Plans
export const PLANS_RECIEVED = 'PLANS_RECIEVED';
export const USER_PLAN_RECEIVED = 'USER_PLAN_RECEIVED';

// Performers
export const PERFORMERS_RECIEVED = 'PERFORMERS_RECIEVED';
export const PERFORMERS_PRO_RECIEVED = 'PERFORMERS_PRO_RECIEVED';
export const PERFORMERS_BUSINESS_RECIEVED = 'PERFORMERS_BUSINESS_RECIEVED';
export const PERFORMERS_FILTER_RECIEVED = 'PERFORMERS_FILTER_RECIEVED';
export const PERFORMERS_LOADED = 'PERFORMERS_LOADED';
export const PERFORMERS_PRO_LOADED = 'PERFORMERS_PRO_LOADED';
export const PERFORMERS_BUSINESS_LOADED = 'PERFORMERS_BUSINESS_LOADED';
export const PERFORMERS_FILTER_CHANGED = 'PERFORMERS_FILTER_CHANGED';
export const PERFORMERS_FILTER_LOADED = 'PERFORMERS_FILTER_LOADED';
export const PERFORMERS_CATALOG_FILTER_TAGS_RECIEVED = 'PERFORMERS_CATALOG_FILTER_TAGS_RECIEVED';

// Finance
export const FINANCE_ACCOUNTS_RECIEVED = 'FINANCE_ACCOUNTS_RECIEVED';
export const FINANCE_ACCOUNT_RECIEVED = 'FINANCE_ACCOUNT_RECIEVED';
export const FINANCE_ACCOUNTS_LOADING_STARTED = 'FINANCE_ACCOUNTS_LOADING_STARTED';
export const FINANCE_BUYPLAN_RECIEVED = 'FINANCE_BUYPLAN_RECIEVED';
export const FINANCE_ORDER_HASH_RECIEVED = 'FINANCE_ORDER_HASH_RECIEVED';
export const FINANCE_ORDER_DATA_RECIEVED = 'FINANCE_ORDER_DATA_RECIEVED';
export const FINANCE_REFILL_RECIEVED = 'FINANCE_REFILL_RECIEVED';

export const REDIRECT_LOGGED_IN = 'REDIRECT_LOGGED_IN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';



export const ARTICLES_RECIEVED = 'ARTICLES_RECIEVED';
export const REDIRECT_DATA_RECIEVED = 'REDIRECT_DATA_RECIEVED';
export const ARTICLES_ADDED = 'ARTICLES_ADDED';
export const ARTICLE_VISITED = 'ARTICLE_VISITED';